server:
  servlet:
    context-path: /api/v1
  port: 8082

management:
  server:
    port: 9092

spring:
  application:
    name: adapter
  main:
    banner-mode: off
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    ru.gurok.adapter: INFO
